openapi: 3.0.1
info:
  title: Puissance 4 API
  version: "1.0"
servers:
- url: //localhost:4444/
tags:
- description: Game Controller
  name: Puissance 4 API
- description: Basic Error Controller
  name: basic-error-controller
paths:
  /api/puissance4/ended:
    get:
      deprecated: false
      operationId: isGameEndedUsingGET
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: boolean
          description: OK
      summary: Vérifie si la partie est terminée
      tags:
      - Puissance 4 API
      x-accepts: '*/*'
  /api/puissance4/initialize:
    post:
      deprecated: false
      operationId: initializeGameUsingPOST
      parameters:
      - description: nomJoueur1
        in: query
        name: nomJoueur1
        required: true
        schema:
          type: string
      - description: nomJoueur2
        in: query
        name: nomJoueur2
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: OK
      summary: Initialise une nouvelle partie de Puissance 4
      tags:
      - Puissance 4 API
      x-accepts: application/json
  /api/puissance4/play:
    post:
      deprecated: false
      operationId: playPieceUsingPOST
      parameters:
      - description: column
        in: query
        name: column
        required: true
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            '*/*':
              schema:
                format: int32
                type: integer
          description: OK
      summary: Effectue un coup dans la colonne spécifiée
      tags:
      - Puissance 4 API
      x-accepts: '*/*'
  /api/puissance4/winner:
    get:
      deprecated: false
      operationId: getWinnerUsingGET
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Joueur'
          description: OK
      summary: Obtient le gagnant de la partie (ou null si la partie n'est pas terminée)
      tags:
      - Puissance 4 API
      x-accepts: '*/*'
  /error:
    delete:
      deprecated: false
      operationId: errorUsingDELETE
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
    get:
      deprecated: false
      operationId: errorUsingGET
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
    head:
      deprecated: false
      operationId: errorUsingHEAD
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
    options:
      deprecated: false
      operationId: errorUsingOPTIONS
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
    patch:
      deprecated: false
      operationId: errorUsingPATCH
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
    post:
      deprecated: false
      operationId: errorUsingPOST
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
    put:
      deprecated: false
      operationId: errorUsingPUT
      responses:
        "200":
          content:
            '*/*':
              schema:
                additionalProperties:
                  properties: {}
                  type: object
                type: object
          description: OK
      summary: error
      tags:
      - basic-error-controller
      x-accepts: '*/*'
components:
  schemas:
    Joueur:
      example:
        id: 0
        nom: nom
      properties:
        id:
          format: int32
          type: integer
        nom:
          type: string
      title: Joueur
      type: object
    ModelAndView:
      properties:
        empty:
          type: boolean
        model:
          properties: {}
          type: object
        modelMap:
          additionalProperties:
            properties: {}
            type: object
          type: object
        reference:
          type: boolean
        status:
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
          type: string
        view:
          $ref: '#/components/schemas/View'
        viewName:
          type: string
      title: ModelAndView
      type: object
    View:
      properties:
        contentType:
          type: string
      title: View
      type: object

